version: '3.8'

# Term Challenge CLI
# For validator setup, see: https://github.com/PlatformNetwork/platform

services:
  term-cli:
    build: .
    environment:
      - VALIDATOR_RPC_URL=http://host.docker.internal:8080
      - RUST_LOG=info
    extra_hosts:
      - "host.docker.internal:host-gateway"
